// src/pages/LegacyVault.jsx
import { useState } from 'react'
import { Landmark, TrendingUp, Shield, Home, Plus, Trash2, ChevronRight, FileText, AlertTriangle, Download } from 'lucide-react'

// ── PDF Export ─────────────────────────────────────────────────────────────────

function exportPDF(bankItems, investItems, insureItems, propertyItems) {
  const val = (v) => v || '—'

  const sectionHeader = (title, color) => `
    <div style="margin: 28px 0 12px; border-left: 4px solid ${color}; padding-left: 12px;">
      <h2 style="font-family: Georgia, serif; font-size: 17px; color: #3F3A34; margin: 0;">${title}</h2>
    </div>`

  const row = (label, value) => `
    <div style="display: flex; gap: 8px; margin-bottom: 6px;">
      <span style="font-family: Arial, sans-serif; font-size: 11px; color: #8C8279; text-transform: uppercase; letter-spacing: 0.05em; min-width: 140px; padding-top: 1px;">${label}</span>
      <span style="font-family: Arial, sans-serif; font-size: 13px; color: #3F3A34; font-weight: 500;">${val(value)}</span>
    </div>`

  const card = (title, color, fields) => `
    <div style="border: 1px solid #EAE0D5; border-radius: 10px; padding: 16px; margin-bottom: 10px; background: #FAF6F0;">
      <div style="font-family: Arial, sans-serif; font-size: 11px; font-weight: 700; color: ${color}; text-transform: uppercase; letter-spacing: 0.06em; margin-bottom: 12px;">${title}</div>
      ${fields}
    </div>`

  const bankHTML = bankItems.map((b, i) => card(`Bank Account ${i + 1}`, '#6E8B78',
    row('Bank Name', b.bankName) + row('Account Type', b.accountType) +
    row('Account Number', b.accountNumber) + row('IFSC Code', b.ifsc) +
    row('Branch', b.branch) + row('Nominee Registered', b.nomineeRegistered)
  )).join('')

  const investHTML = investItems.map((v, i) => card(`Investment ${i + 1}`, '#7A8BA0',
    row('Type', v.type) + row('Platform / AMC', v.platform) +
    row('Folio / Account No.', v.folioNumber) + row('Approx. Value (₹)', v.approxValue) +
    row('Registered Email', v.loginEmail) + row('Nominee Registered', v.nomineeRegistered)
  )).join('')

  const insureHTML = insureItems.map((ins, i) => card(`Insurance Policy ${i + 1}`, '#A08B6E',
    row('Type', ins.type) + row('Company', ins.company) +
    row('Policy Number', ins.policyNumber) + row('Sum Assured (₹)', ins.sumAssured) +
    row('Premium Due', ins.premiumDue) + row('Agent Contact', ins.agentContact)
  )).join('')

  const propHTML = propertyItems.map((p, i) => card(`Asset ${i + 1}`, '#8B6E7A',
    row('Type', p.type) + row('Approx. Value (₹)', p.approxValue) + row('Address / Details', p.address)
  )).join('')

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8" /><title>LegacyVault — Financial Asset Record</title>
    <style>@media print { body { margin: 0; } } body { background: #F5F0E8; margin: 0; padding: 32px; }</style>
    </head><body>
    <div style="max-width: 720px; margin: 0 auto; background: white; border-radius: 16px; padding: 40px; box-shadow: 0 2px 20px rgba(0,0,0,0.08);">
      <div style="border-bottom: 2px solid #EAE0D5; padding-bottom: 20px; margin-bottom: 8px;">
        <h1 style="font-family: Georgia, serif; font-size: 26px; color: #3F3A34; margin: 0 0 6px;">LegacyVault</h1>
        <p style="font-family: Arial, sans-serif; font-size: 13px; color: #8C8279; margin: 0;">Financial Asset Record · Generated ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</p>
        <p style="font-family: Arial, sans-serif; font-size: 12px; color: #B0A89F; margin: 8px 0 0;">Keep this document in a secure location and share only with trusted family members or your legal advisor.</p>
      </div>
      ${sectionHeader('Bank Accounts', '#6E8B78')}
      ${bankHTML || '<p style="font-family:Arial,sans-serif;font-size:13px;color:#ADA69F;">No bank accounts added.</p>'}
      ${sectionHeader('Investments', '#7A8BA0')}
      ${investHTML || '<p style="font-family:Arial,sans-serif;font-size:13px;color:#ADA69F;">No investments added.</p>'}
      ${sectionHeader('Insurance Policies', '#A08B6E')}
      ${insureHTML || '<p style="font-family:Arial,sans-serif;font-size:13px;color:#ADA69F;">No insurance policies added.</p>'}
      ${sectionHeader('Property & Assets', '#8B6E7A')}
      ${propHTML || '<p style="font-family:Arial,sans-serif;font-size:13px;color:#ADA69F;">No property or assets added.</p>'}
      <div style="margin-top: 36px; border-top: 1px solid #EAE0D5; padding-top: 16px;">
        <p style="font-family: Arial, sans-serif; font-size: 11px; color: #B0A89F; text-align: center;">Generated by Sahara · This document contains sensitive financial information. Store securely.</p>
      </div>
    </div></body></html>`

  const win = window.open('', '_blank')
  win.document.write(html)
  win.document.close()
  win.focus()
  setTimeout(() => win.print(), 500)
}

const uid = () => Math.random().toString(36).slice(2, 8)

const TABS = [
  { key: 'bank',     label: 'Bank Accounts',  icon: Landmark,   accent: '#6E8B78' },
  { key: 'invest',   label: 'Investments',    icon: TrendingUp, accent: '#7A8BA0' },
  { key: 'insure',   label: 'Insurance',      icon: Shield,     accent: '#A08B6E' },
  { key: 'property', label: 'Property',       icon: Home,       accent: '#8B6E7A' },
  { key: 'docs',     label: 'Document Guide', icon: FileText,   accent: '#7A7A7A' },
]

const defaultBank     = () => ({ id: uid(), bankName: '', accountType: 'Savings', accountNumber: '', ifsc: '', branch: '', nomineeRegistered: 'Yes' })
const defaultInvest   = () => ({ id: uid(), type: 'Mutual Fund', platform: '', folioNumber: '', approxValue: '', loginEmail: '', nomineeRegistered: 'Yes' })
const defaultInsure   = () => ({ id: uid(), type: 'Life Insurance', company: '', policyNumber: '', sumAssured: '', premiumDue: '', agentContact: '' })
const defaultProperty = () => ({ id: uid(), type: 'Residential Property', approxValue: '', address: '' })

const inputStyle = {
  fontFamily: "'DM Sans', sans-serif",
  padding: '9px 14px',
  borderRadius: '10px',
  border: '1px solid #DDD6CC',
  backgroundColor: '#F5F0E8',
  color: '#3F3A34',
  fontSize: '14px',
  outline: 'none',
  width: '100%',
  boxSizing: 'border-box',
  transition: 'border-color 0.2s',
}

const selectStyle = { ...inputStyle, cursor: 'pointer' }

function Field({ label, children }) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
      <label style={{ fontFamily: "'DM Sans', sans-serif", fontSize: '11px', fontWeight: '600', color: '#8C8279', textTransform: 'uppercase', letterSpacing: '0.06em' }}>
        {label}
      </label>
      {children}
    </div>
  )
}

function AssetCard({ label, onRemove, children, accent }) {
  return (
    <div style={{ border: '1px solid #EAE0D5', borderRadius: '14px', padding: '20px', backgroundColor: '#FAF6F0', marginBottom: '12px' }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '16px' }}>
        <span style={{ fontFamily: "'DM Sans', sans-serif", fontSize: '12px', fontWeight: '600', color: accent, backgroundColor: `${accent}18`, border: `1px solid ${accent}30`, borderRadius: '20px', padding: '3px 12px' }}>
          {label}
        </span>
        <button
          onClick={onRemove}
          style={{ fontFamily: "'DM Sans', sans-serif", fontSize: '12px', color: '#8C8279', backgroundColor: 'transparent', border: '1px solid #DDD6CC', borderRadius: '8px', padding: '4px 10px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '4px' }}
        >
          <Trash2 size={11} /> Remove
        </button>
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '14px' }}>
        {children}
      </div>
    </div>
  )
}

function AddButton({ onClick, label, accent }) {
  return (
    <button
      onClick={onClick}
      style={{ fontFamily: "'DM Sans', sans-serif", fontSize: '13px', fontWeight: '500', color: accent, backgroundColor: 'transparent', border: `1.5px dashed ${accent}60`, borderRadius: '12px', padding: '12px', width: '100%', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '6px', marginTop: '8px' }}
    >
      <Plus size={14} /> {label}
    </button>
  )
}

function SectionDesc({ children }) {
  return <p style={{ fontFamily: "'DM Sans', sans-serif", fontSize: '14px', color: '#6B6560', marginBottom: '18px', lineHeight: '1.6' }}>{children}</p>
}

function BankSection({ items, setItems }) {
  const update = (id, f, v) => setItems(p => p.map(i => i.id === id ? { ...i, [f]: v } : i))
  const remove = (id) => items.length > 1 && setItems(p => p.filter(i => i.id !== id))
  return (
    <div>
      <SectionDesc>Record all bank accounts, fixed deposits, and recurring deposits held by the deceased.</SectionDesc>
      {items.map(item => (
        <AssetCard key={item.id} label="Bank Account" accent="#6E8B78" onRemove={() => remove(item.id)}>
          <Field label="Bank Name"><input style={inputStyle} placeholder="e.g. HDFC Bank" value={item.bankName} onChange={e => update(item.id, 'bankName', e.target.value)} /></Field>
          <Field label="Account Type"><select style={selectStyle} value={item.accountType} onChange={e => update(item.id, 'accountType', e.target.value)}>{['Savings','Current','Fixed Deposit','Recurring Deposit'].map(o => <option key={o}>{o}</option>)}</select></Field>
          <Field label="Account Number"><input style={inputStyle} placeholder="Account number" value={item.accountNumber} onChange={e => update(item.id, 'accountNumber', e.target.value)} /></Field>
          <Field label="IFSC Code"><input style={inputStyle} placeholder="IFSC Code" value={item.ifsc} onChange={e => update(item.id, 'ifsc', e.target.value)} /></Field>
          <Field label="Branch"><input style={inputStyle} placeholder="Branch name & city" value={item.branch} onChange={e => update(item.id, 'branch', e.target.value)} /></Field>
          <Field label="Nominee Registered?"><select style={selectStyle} value={item.nomineeRegistered} onChange={e => update(item.id, 'nomineeRegistered', e.target.value)}>{['Yes','No','Not Sure'].map(o => <option key={o}>{o}</option>)}</select></Field>
        </AssetCard>
      ))}
      <AddButton onClick={() => setItems(p => [...p, defaultBank()])} label="Add Another Bank Account" accent="#6E8B78" />
    </div>
  )
}

function InvestSection({ items, setItems }) {
  const update = (id, f, v) => setItems(p => p.map(i => i.id === id ? { ...i, [f]: v } : i))
  const remove = (id) => items.length > 1 && setItems(p => p.filter(i => i.id !== id))
  return (
    <div>
      <SectionDesc>Document mutual funds, shares, EPF, PPF, NPS, and other investment holdings.</SectionDesc>
      {items.map(item => (
        <AssetCard key={item.id} label="Investment" accent="#7A8BA0" onRemove={() => remove(item.id)}>
          <Field label="Investment Type"><select style={selectStyle} value={item.type} onChange={e => update(item.id, 'type', e.target.value)}>{['Mutual Fund','Shares / Equity','NPS','PPF','EPF','Bonds','Demat Account'].map(o => <option key={o}>{o}</option>)}</select></Field>
          <Field label="Platform / AMC"><input style={inputStyle} placeholder="e.g. Groww, Zerodha" value={item.platform} onChange={e => update(item.id, 'platform', e.target.value)} /></Field>
          <Field label="Folio / Account Number"><input style={inputStyle} placeholder="Folio or account number" value={item.folioNumber} onChange={e => update(item.id, 'folioNumber', e.target.value)} /></Field>
          <Field label="Approximate Value (₹)"><input style={inputStyle} placeholder="e.g. 1,00,000" value={item.approxValue} onChange={e => update(item.id, 'approxValue', e.target.value)} /></Field>
          <Field label="Registered Email"><input style={inputStyle} placeholder="Email used to login" value={item.loginEmail} onChange={e => update(item.id, 'loginEmail', e.target.value)} /></Field>
          <Field label="Nominee Registered?"><select style={selectStyle} value={item.nomineeRegistered} onChange={e => update(item.id, 'nomineeRegistered', e.target.value)}>{['Yes','No','Not Sure'].map(o => <option key={o}>{o}</option>)}</select></Field>
        </AssetCard>
      ))}
      <AddButton onClick={() => setItems(p => [...p, defaultInvest()])} label="Add Another Investment" accent="#7A8BA0" />
    </div>
  )
}

function InsureSection({ items, setItems }) {
  const update = (id, f, v) => setItems(p => p.map(i => i.id === id ? { ...i, [f]: v } : i))
  const remove = (id) => items.length > 1 && setItems(p => p.filter(i => i.id !== id))
  return (
    <div>
      <SectionDesc>Record all life, term, health, and vehicle insurance policies.</SectionDesc>
      {items.map(item => (
        <AssetCard key={item.id} label="Insurance Policy" accent="#A08B6E" onRemove={() => remove(item.id)}>
          <Field label="Insurance Type"><select style={selectStyle} value={item.type} onChange={e => update(item.id, 'type', e.target.value)}>{['Life Insurance','Term Insurance','Health / Mediclaim','ULIP','Vehicle Insurance'].map(o => <option key={o}>{o}</option>)}</select></Field>
          <Field label="Company Name"><input style={inputStyle} placeholder="e.g. LIC, HDFC Life" value={item.company} onChange={e => update(item.id, 'company', e.target.value)} /></Field>
          <Field label="Policy Number"><input style={inputStyle} placeholder="Policy number" value={item.policyNumber} onChange={e => update(item.id, 'policyNumber', e.target.value)} /></Field>
          <Field label="Sum Assured (₹)"><input style={inputStyle} placeholder="e.g. 50,00,000" value={item.sumAssured} onChange={e => update(item.id, 'sumAssured', e.target.value)} /></Field>
          <Field label="Premium Due Date"><input style={{ ...inputStyle, colorScheme: 'light' }} type="month" value={item.premiumDue} onChange={e => update(item.id, 'premiumDue', e.target.value)} /></Field>
          <Field label="Agent Contact"><input style={inputStyle} placeholder="Agent name & phone" value={item.agentContact} onChange={e => update(item.id, 'agentContact', e.target.value)} /></Field>
        </AssetCard>
      ))}
      <AddButton onClick={() => setItems(p => [...p, defaultInsure()])} label="Add Another Policy" accent="#A08B6E" />
    </div>
  )
}

function PropertySection({ items, setItems }) {
  const update = (id, f, v) => setItems(p => p.map(i => i.id === id ? { ...i, [f]: v } : i))
  const remove = (id) => items.length > 1 && setItems(p => p.filter(i => i.id !== id))
  return (
    <div>
      <SectionDesc>List all physical assets including property, vehicles, gold, and other valuables.</SectionDesc>

      <div style={{ backgroundColor: '#FDF6EC', border: '1px solid #E8D5B0', borderRadius: '12px', padding: '14px 16px', marginBottom: '18px', display: 'flex', gap: '10px', alignItems: 'flex-start' }}>
        <AlertTriangle size={15} style={{ color: '#A08B6E', marginTop: '2px', flexShrink: 0 }} />
        <p style={{ fontFamily: "'DM Sans', sans-serif", fontSize: '13px', color: '#7A6348', lineHeight: '1.5' }}>Always consult a legal advocate for property transfers. The process varies by state.</p>
      </div>

      <div style={{ border: '1px solid #EAE0D5', borderRadius: '14px', padding: '20px', backgroundColor: '#FAF6F0', marginBottom: '18px' }}>
        <p style={{ fontFamily: "'Playfair Display', serif", fontSize: '15px', color: '#3F3A34', marginBottom: '14px' }}>How to transfer property</p>
        {[
          { n: '1', title: 'If there is a Will — Probate', desc: 'File a Probate Application in the High Court. Once validated, apply for property mutation at the Sub-Registrar office.' },
          { n: '2', title: 'If there is no Will', desc: 'Obtain a Legal Heir Certificate from the Tehsildar or Court. Then apply for a Succession Certificate and submit a mutation application.' },
          { n: '3', title: 'If there is a Home Loan', desc: 'Notify the bank immediately. If a loan insurance policy exists, file a claim. The nominee may continue EMI payments or arrange prepayment.' },
        ].map(step => (
          <div key={step.n} style={{ display: 'flex', gap: '12px', marginBottom: '12px' }}>
            <div style={{ width: '24px', height: '24px', borderRadius: '50%', backgroundColor: 'rgba(110,139,120,0.15)', color: '#6E8B78', fontSize: '12px', fontWeight: '700', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, fontFamily: "'DM Sans', sans-serif" }}>{step.n}</div>
            <div>
              <p style={{ fontFamily: "'DM Sans', sans-serif", fontSize: '13px', fontWeight: '600', color: '#3F3A34' }}>{step.title}</p>
              <p style={{ fontFamily: "'DM Sans', sans-serif", fontSize: '12px', color: '#6B6560', marginTop: '2px', lineHeight: '1.5' }}>{step.desc}</p>
            </div>
          </div>
        ))}
      </div>

      {items.map(item => (
        <AssetCard key={item.id} label="Asset" accent="#8B6E7A" onRemove={() => remove(item.id)}>
          <Field label="Asset Type"><select style={selectStyle} value={item.type} onChange={e => update(item.id, 'type', e.target.value)}>{['Residential Property','Commercial Property','Agricultural Land','Vehicle','Gold / Silver','Fixed Deposit','Other'].map(o => <option key={o}>{o}</option>)}</select></Field>
          <Field label="Approximate Value (₹)"><input style={inputStyle} placeholder="e.g. 50,00,000" value={item.approxValue} onChange={e => update(item.id, 'approxValue', e.target.value)} /></Field>
          <div style={{ gridColumn: 'span 2' }}>
            <Field label="Address / Details"><input style={inputStyle} placeholder="Property address or description" value={item.address} onChange={e => update(item.id, 'address', e.target.value)} /></Field>
          </div>
        </AssetCard>
      ))}
      <AddButton onClick={() => setItems(p => [...p, defaultProperty()])} label="Add Another Asset" accent="#8B6E7A" />
    </div>
  )
}

function DocsSection() {
  const rows = [
    { task: 'Death Certificate',    docs: 'Hospital certificate, Aadhaar, Proof of residence' },
    { task: 'Bank Claim',           docs: 'Death Certificate, Nominee KYC, Claim Form, Passbook' },
    { task: 'LIC / Insurance',      docs: 'Death Certificate, Policy Bond, Nominee KYC, Claim Form' },
    { task: 'Mutual Fund Transfer', docs: 'Death Certificate, Nominee KYC, Folio Number, Transmission Form' },
    { task: 'Property Mutation',    docs: 'Death Certificate, Will / Succession Certificate, NOC, Photo ID' },
    { task: 'Vehicle Transfer',     docs: 'Death Certificate, RC Book, Insurance, NOC, Legal Heir Certificate' },
    { task: 'EPF Claim',            docs: 'Death Certificate, Form 20, Nominee KYC, Bank Details' },
  ]
  return (
    <div>
      <SectionDesc>A quick reference for which documents are needed for each process.</SectionDesc>
      <div style={{ border: '1px solid #EAE0D5', borderRadius: '14px', overflow: 'hidden' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse' }}>
          <thead>
            <tr style={{ backgroundColor: '#F5F0E8', borderBottom: '1px solid #EAE0D5' }}>
              <th style={{ fontFamily: "'DM Sans', sans-serif", fontSize: '11px', fontWeight: '600', color: '#8C8279', textTransform: 'uppercase', letterSpacing: '0.06em', textAlign: 'left', padding: '12px 16px', width: '30%' }}>Task</th>
              <th style={{ fontFamily: "'DM Sans', sans-serif", fontSize: '11px', fontWeight: '600', color: '#8C8279', textTransform: 'uppercase', letterSpacing: '0.06em', textAlign: 'left', padding: '12px 16px' }}>Required Documents</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((row, i) => (
              <tr key={i} style={{ borderBottom: i < rows.length - 1 ? '1px solid #EAE0D5' : 'none', backgroundColor: i % 2 === 0 ? '#FFFFFF' : '#FAF6F0' }}>
                <td style={{ fontFamily: "'DM Sans', sans-serif", fontSize: '13px', fontWeight: '600', color: '#3F3A34', padding: '12px 16px' }}>{row.task}</td>
                <td style={{ fontFamily: "'DM Sans', sans-serif", fontSize: '13px', color: '#6B6560', padding: '12px 16px' }}>{row.docs}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}

export default function LegacyVault() {
  const [activeTab, setActiveTab] = useState('bank')
  const [bankItems,     setBankItems]     = useState([defaultBank()])
  const [investItems,   setInvestItems]   = useState([defaultInvest()])
  const [insureItems,   setInsureItems]   = useState([defaultInsure()])
  const [propertyItems, setPropertyItems] = useState([defaultProperty()])

  const counts = { bank: bankItems.length, invest: investItems.length, insure: insureItems.length, property: propertyItems.length, docs: null }
  const active = TABS.find(t => t.key === activeTab)

  return (
    <div style={{ minHeight: '100vh', backgroundColor: '#F5F0E8', padding: '32px 24px' }}>
      <div style={{ maxWidth: '800px', margin: '0 auto' }}>

        {/* Breadcrumb */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '16px' }}>
          <span style={{ fontFamily: "'DM Sans', sans-serif", fontSize: '13px', color: '#8C8279' }}>Finance & Bank Accounts</span>
          <ChevronRight size={13} style={{ color: '#8C8279' }} />
          <span style={{ fontFamily: "'DM Sans', sans-serif", fontSize: '13px', color: '#3F3A34', fontWeight: '500' }}>LegacyVault</span>
        </div>

        {/* Page header */}
        <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: '28px', gap: '16px', flexWrap: 'wrap' }}>
          <div>
            <h1 style={{ fontFamily: "'Playfair Display', serif", fontSize: '28px', color: '#3F3A34', marginBottom: '6px' }}>LegacyVault</h1>
            <p style={{ fontFamily: "'DM Sans', sans-serif", fontSize: '14px', color: '#6B6560', lineHeight: '1.6' }}>Document all financial assets so nothing is missed during the settlement process.</p>
          </div>
          <button
            onClick={() => exportPDF(bankItems, investItems, insureItems, propertyItems)}
            style={{ fontFamily: "'DM Sans', sans-serif", fontSize: '14px', fontWeight: '500', color: '#FAF6F0', backgroundColor: '#6E8B78', border: 'none', borderRadius: '12px', padding: '10px 20px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px', whiteSpace: 'nowrap', flexShrink: 0, boxShadow: '0 2px 8px rgba(110,139,120,0.3)' }}
          >
            <Download size={15} /> Download PDF
          </button>
        </div>

        {/* Summary cards */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '12px', marginBottom: '24px' }}>
          {TABS.filter(t => t.key !== 'docs').map(tab => {
            const Icon = tab.icon
            const isActive = activeTab === tab.key
            return (
              <button key={tab.key} onClick={() => setActiveTab(tab.key)} style={{ backgroundColor: isActive ? '#FAF6F0' : '#FFFFFF', border: `1px solid ${isActive ? tab.accent + '60' : '#EAE0D5'}`, borderRadius: '14px', padding: '16px', textAlign: 'left', cursor: 'pointer', boxShadow: isActive ? `0 2px 12px ${tab.accent}20` : 'none', transition: 'all 0.2s' }}>
                <Icon size={16} style={{ color: tab.accent, marginBottom: '8px' }} />
                <p style={{ fontFamily: "'DM Sans', sans-serif", fontSize: '20px', fontWeight: '600', color: '#3F3A34' }}>{counts[tab.key]}</p>
                <p style={{ fontFamily: "'DM Sans', sans-serif", fontSize: '11px', color: '#8C8279', marginTop: '2px' }}>{tab.label}</p>
              </button>
            )
          })}
        </div>

        {/* Tab nav */}
        <div style={{ display: 'flex', gap: '4px', backgroundColor: '#EAE0D5', borderRadius: '14px', padding: '4px', marginBottom: '20px', overflowX: 'auto' }}>
          {TABS.map(tab => {
            const Icon = tab.icon
            const isActive = activeTab === tab.key
            return (
              <button key={tab.key} onClick={() => setActiveTab(tab.key)} style={{ display: 'flex', alignItems: 'center', gap: '6px', padding: '8px 14px', borderRadius: '10px', border: 'none', cursor: 'pointer', fontFamily: "'DM Sans', sans-serif", fontSize: '13px', fontWeight: '500', whiteSpace: 'nowrap', flex: 1, justifyContent: 'center', backgroundColor: isActive ? '#FAF6F0' : 'transparent', color: isActive ? tab.accent : '#8C8279', boxShadow: isActive ? '0 1px 4px rgba(63,58,52,0.08)' : 'none', transition: 'all 0.2s' }}>
                <Icon size={13} />
                {tab.label}
                {counts[tab.key] && (
                  <span style={{ fontSize: '11px', fontWeight: '600', backgroundColor: isActive ? tab.accent + '20' : 'rgba(63,58,52,0.08)', color: isActive ? tab.accent : '#8C8279', borderRadius: '10px', padding: '1px 6px' }}>{counts[tab.key]}</span>
                )}
              </button>
            )
          })}
        </div>

        {/* Content card */}
        <div style={{ backgroundColor: '#FFFFFF', border: '1px solid #EAE0D5', borderRadius: '16px', padding: '24px', boxShadow: '0 2px 16px rgba(63,58,52,0.06)' }}>
          <h2 style={{ fontFamily: "'Playfair Display', serif", fontSize: '18px', color: '#3F3A34', marginBottom: '4px' }}>{active.label}</h2>
          <div style={{ width: '32px', height: '2px', backgroundColor: active.accent, borderRadius: '2px', marginBottom: '20px' }} />
          {activeTab === 'bank'     && <BankSection     items={bankItems}     setItems={setBankItems}     />}
          {activeTab === 'invest'   && <InvestSection   items={investItems}   setItems={setInvestItems}   />}
          {activeTab === 'insure'   && <InsureSection   items={insureItems}   setItems={setInsureItems}   />}
          {activeTab === 'property' && <PropertySection items={propertyItems} setItems={setPropertyItems} />}
          {activeTab === 'docs'     && <DocsSection />}
        </div>

        <p style={{ fontFamily: "'DM Sans', sans-serif", fontSize: '12px', color: '#ADA69F', textAlign: 'center', marginTop: '16px' }}>
          This information is stored locally in your session. Download the PDF to keep a permanent copy.
        </p>
      </div>
    </div>
  )
}